//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.18020.
// 
namespace Exerp.Api.WebServices.SocialAPI {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SocialAPIBinding", Namespace="http://v4.api.eclub.procard.dk/")]
    public partial class SocialAPIService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback createFriendRelationOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteFriendRelationOperationCompleted;
        
        /// <remarks/>
        public SocialAPIService() {
            this.Url = "https://puregym-test.exerp.com/api-v4/SocialAPI";
        }
        
        /// <remarks/>
        public event createFriendRelationCompletedEventHandler createFriendRelationCompleted;
        
        /// <remarks/>
        public event deleteFriendRelationCompletedEventHandler deleteFriendRelationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://v4.api.eclub.procard.dk/", ResponseNamespace="http://v4.api.eclub.procard.dk/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public void createFriendRelation(compositeKey arg0, compositeKey arg1) {
            this.Invoke("createFriendRelation", new object[] {
                        arg0,
                        arg1});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateFriendRelation(compositeKey arg0, compositeKey arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createFriendRelation", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateFriendRelation(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void createFriendRelationAsync(compositeKey arg0, compositeKey arg1) {
            this.createFriendRelationAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void createFriendRelationAsync(compositeKey arg0, compositeKey arg1, object userState) {
            if ((this.createFriendRelationOperationCompleted == null)) {
                this.createFriendRelationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateFriendRelationOperationCompleted);
            }
            this.InvokeAsync("createFriendRelation", new object[] {
                        arg0,
                        arg1}, this.createFriendRelationOperationCompleted, userState);
        }
        
        private void OncreateFriendRelationOperationCompleted(object arg) {
            if ((this.createFriendRelationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createFriendRelationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://v4.api.eclub.procard.dk/", ResponseNamespace="http://v4.api.eclub.procard.dk/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public void deleteFriendRelation(compositeKey arg0, compositeKey arg1) {
            this.Invoke("deleteFriendRelation", new object[] {
                        arg0,
                        arg1});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteFriendRelation(compositeKey arg0, compositeKey arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteFriendRelation", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnddeleteFriendRelation(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void deleteFriendRelationAsync(compositeKey arg0, compositeKey arg1) {
            this.deleteFriendRelationAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void deleteFriendRelationAsync(compositeKey arg0, compositeKey arg1, object userState) {
            if ((this.deleteFriendRelationOperationCompleted == null)) {
                this.deleteFriendRelationOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteFriendRelationOperationCompleted);
            }
            this.InvokeAsync("deleteFriendRelation", new object[] {
                        arg0,
                        arg1}, this.deleteFriendRelationOperationCompleted, userState);
        }
        
        private void OndeleteFriendRelationOperationCompleted(object arg) {
            if ((this.deleteFriendRelationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteFriendRelationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://v4.api.eclub.procard.dk/")]
    public partial class compositeKey {
        
        private int centerField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    public delegate void createFriendRelationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    public delegate void deleteFriendRelationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}
